//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SundayWorshipPPTMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SundayWorshipPPTMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bgDefault1 {
            get {
                object obj = ResourceManager.GetObject("bgDefault1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   /Resources/bibleCover.jpg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriBibleCover {
            get {
                return ResourceManager.GetString("BGUriBibleCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/bibleTextLight.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriBibleTextLight {
            get {
                return ResourceManager.GetString("BGUriBibleTextLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/bibleTextOriginal.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriBibleTextOrigin {
            get {
                return ResourceManager.GetString("BGUriBibleTextOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/birthday01.jpg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriBirthday01 {
            get {
                return ResourceManager.GetString("BGUriBirthday01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/birthday02.jpg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriBirthday02 {
            get {
                return ResourceManager.GetString("BGUriBirthday02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/cross01.jpg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriCross01 {
            get {
                return ResourceManager.GetString("BGUriCross01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/cross02.jpg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriCross02 {
            get {
                return ResourceManager.GetString("BGUriCross02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/cutImg01.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriCutImg01 {
            get {
                return ResourceManager.GetString("BGUriCutImg01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/cutImg02.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriCutImg02 {
            get {
                return ResourceManager.GetString("BGUriCutImg02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/cutImg03.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriCutImg03 {
            get {
                return ResourceManager.GetString("BGUriCutImg03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/dedication.jpg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriDedication {
            get {
                return ResourceManager.GetString("BGUriDedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/bgDefault.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriDefault {
            get {
                return ResourceManager.GetString("BGUriDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/dsong00.jpg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriDSong {
            get {
                return ResourceManager.GetString("BGUriDSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/intro.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriIntro {
            get {
                return ResourceManager.GetString("BGUriIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/pray01.jpg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriPray01 {
            get {
                return ResourceManager.GetString("BGUriPray01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/pray02.jpg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriPray02 {
            get {
                return ResourceManager.GetString("BGUriPray02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/preach.jpg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BGUriPreach {
            get {
                return ResourceManager.GetString("BGUriPreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bibleCover {
            get {
                object obj = ResourceManager.GetObject("bibleCover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bibleIcon {
            get {
                object obj = ResourceManager.GetObject("bibleIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bibleTextLight {
            get {
                object obj = ResourceManager.GetObject("bibleTextLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bibleTextOriginal {
            get {
                object obj = ResourceManager.GetObject("bibleTextOriginal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap birthday01 {
            get {
                object obj = ResourceManager.GetObject("birthday01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap birthday02 {
            get {
                object obj = ResourceManager.GetObject("birthday02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cross01 {
            get {
                object obj = ResourceManager.GetObject("cross01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cross02 {
            get {
                object obj = ResourceManager.GetObject("cross02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cutImg01 {
            get {
                object obj = ResourceManager.GetObject("cutImg01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cutImg02 {
            get {
                object obj = ResourceManager.GetObject("cutImg02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cutImg03 {
            get {
                object obj = ResourceManager.GetObject("cutImg03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dedication {
            get {
                object obj = ResourceManager.GetObject("dedication", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dsong01 {
            get {
                object obj = ResourceManager.GetObject("dsong01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dsong02 {
            get {
                object obj = ResourceManager.GetObject("dsong02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dsong03 {
            get {
                object obj = ResourceManager.GetObject("dsong03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dsongBG {
            get {
                object obj = ResourceManager.GetObject("dsongBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap folder_management {
            get {
                object obj = ResourceManager.GetObject("folder_management", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap heart {
            get {
                object obj = ResourceManager.GetObject("heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   HKEY_Current_User\Software\HNC\HwpCtrl\Modules과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HncRoot {
            get {
                return ResourceManager.GetString("HncRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon icon_default_gold {
            get {
                object obj = ResourceManager.GetObject("icon_default_gold", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon icon_default_navy {
            get {
                object obj = ResourceManager.GetObject("icon_default_navy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   /Resources/bibleIcon.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImgUriBibleIcon {
            get {
                return ResourceManager.GetString("ImgUriBibleIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/dsong01.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImgUriDSong01 {
            get {
                return ResourceManager.GetString("ImgUriDSong01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/dsong02.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImgUriDSong02 {
            get {
                return ResourceManager.GetString("ImgUriDSong02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/dsong03.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImgUriDSong03 {
            get {
                return ResourceManager.GetString("ImgUriDSong03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/seal.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImgUriSeal {
            get {
                return ResourceManager.GetString("ImgUriSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap intro {
            get {
                object obj = ResourceManager.GetObject("intro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   파일이름을 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설교ppt를 확인하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidPreachPPT {
            get {
                return ResourceManager.GetString("InvalidPreachPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   템플릿ppt를 확인하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidPresentationTemplate {
            get {
                return ResourceManager.GetString("InvalidPresentationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업폴더를 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidWorkingDirectory {
            get {
                return ResourceManager.GetString("InvalidWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap logo01 {
            get {
                object obj = ResourceManager.GetObject("logo01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap logo02 {
            get {
                object obj = ResourceManager.GetObject("logo02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap logo03 {
            get {
                object obj = ResourceManager.GetObject("logo03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   추가된 곡이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoPraise {
            get {
                return ResourceManager.GetString("NoPraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대표기도자를 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoPrayer {
            get {
                return ResourceManager.GetString("NoPrayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설교제목을 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoTitle {
            get {
                return ResourceManager.GetString("NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap open_folder {
            get {
                object obj = ResourceManager.GetObject("open_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap powerpoint {
            get {
                object obj = ResourceManager.GetObject("powerpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap pray01 {
            get {
                object obj = ResourceManager.GetObject("pray01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap pray02 {
            get {
                object obj = ResourceManager.GetObject("pray02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap preach {
            get {
                object obj = ResourceManager.GetObject("preach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap seal {
            get {
                object obj = ResourceManager.GetObject("seal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap search_vid {
            get {
                object obj = ResourceManager.GetObject("search_vid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   아래 목록을 순서대로 실행하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskErrorCheckMessage {
            get {
                return ResourceManager.GetString("TaskErrorCheckMessage", resourceCulture);
            }
        }
    }
}
