//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SundayWorshipPPTMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SundayWorshipPPTMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   HKEY_Current_User\Software\HNC\HwpCtrl\Modules과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HncRoot {
            get {
                return ResourceManager.GetString("HncRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일이름을 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설교ppt를 확인하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidPreachPPT {
            get {
                return ResourceManager.GetString("InvalidPreachPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   템플릿ppt를 확인하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidPresentationTemplate {
            get {
                return ResourceManager.GetString("InvalidPresentationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업폴더를 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidWorkingDirectory {
            get {
                return ResourceManager.GetString("InvalidWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가된 곡이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoPraise {
            get {
                return ResourceManager.GetString("NoPraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아래 목록을 순서대로 실행하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskErrorCheckMessage {
            get {
                return ResourceManager.GetString("TaskErrorCheckMessage", resourceCulture);
            }
        }
    }
}
